-- Schema is maintained exclusively by supabase/migrations in filename order.
-- The former standalone snapshot enabled public access and is intentionally retired.
-- For account ownership setup, legacy backfill, and verification see:
-- docs/account-ownership.md
-- Do not reapply historical public policies to an existing database.
