import type { Exercise, PlanDay, PlanExercise } from './model';

export const PRESET_EXERCISES: Exercise[] = [
  // Chest & Push-up Variations
  {
    id: 'ex-1',
    name: 'Incline Chest Press',
    category: 'Chest',
    defaultSets: 4,
    defaultReps: '8-12',
  },
  { id: 'ex-2', name: 'Flat Chest Press', category: 'Chest', defaultSets: 4, defaultReps: '8-12' },
  {
    id: 'ex-3',
    name: 'Barbell Bench Press',
    category: 'Chest',
    defaultSets: 4,
    defaultReps: '8-10',
  },
  { id: 'ex-4', name: 'Chest Flyes', category: 'Chest', defaultSets: 3, defaultReps: '12-15' },
  {
    id: 'ex-5',
    name: 'Standard Push-ups',
    category: 'Chest',
    defaultSets: 3,
    defaultReps: '15-20',
  },
  {
    id: 'ex-35',
    name: 'Decline Push-ups (Upper Chest)',
    category: 'Chest',
    defaultSets: 3,
    defaultReps: '12-15',
  },
  {
    id: 'ex-36',
    name: 'Incline Push-ups (Lower Chest)',
    category: 'Chest',
    defaultSets: 3,
    defaultReps: '15-20',
  },
  {
    id: 'ex-37',
    name: 'Diamond Push-ups (Triceps & Inner Chest)',
    category: 'Chest',
    defaultSets: 3,
    defaultReps: '10-12',
  },
  {
    id: 'ex-38',
    name: 'Wide-Grip Push-ups (Outer Chest)',
    category: 'Chest',
    defaultSets: 3,
    defaultReps: '12-15',
  },
  {
    id: 'ex-39',
    name: 'Pike Push-ups (Shoulders)',
    category: 'Shoulders',
    defaultSets: 3,
    defaultReps: '10-12',
  },
  {
    id: 'ex-40',
    name: 'Archer Push-ups (Unilateral Chest)',
    category: 'Chest',
    defaultSets: 3,
    defaultReps: '8-10 per side',
  },

  // Back
  {
    id: 'ex-6',
    name: 'Pull-ups / Lat Pulldown',
    category: 'Back',
    defaultSets: 4,
    defaultReps: '8-12',
  },
  {
    id: 'ex-7',
    name: 'Barbell Bent-Over Row',
    category: 'Back',
    defaultSets: 4,
    defaultReps: '8-10',
  },
  { id: 'ex-8', name: 'Seated Cable Row', category: 'Back', defaultSets: 3, defaultReps: '10-12' },
  {
    id: 'ex-9',
    name: 'Single-Arm Dumbbell Row',
    category: 'Back',
    defaultSets: 3,
    defaultReps: '10-12',
  },

  // Legs
  { id: 'ex-10', name: 'Barbell Squats', category: 'Legs', defaultSets: 4, defaultReps: '8-10' },
  { id: 'ex-11', name: 'Leg Press', category: 'Legs', defaultSets: 3, defaultReps: '10-12' },
  { id: 'ex-12', name: 'Romanian Deadlift', category: 'Legs', defaultSets: 4, defaultReps: '8-10' },
  { id: 'ex-13', name: 'Leg Extension', category: 'Legs', defaultSets: 3, defaultReps: '12-15' },
  { id: 'ex-14', name: 'Lying Leg Curl', category: 'Legs', defaultSets: 3, defaultReps: '12-15' },
  { id: 'ex-15', name: 'Calf Raises', category: 'Legs', defaultSets: 4, defaultReps: '15-20' },

  // Shoulders
  {
    id: 'ex-16',
    name: 'Shoulder Press',
    category: 'Shoulders',
    defaultSets: 4,
    defaultReps: '8-12',
  },
  {
    id: 'ex-17',
    name: 'Lateral Raises',
    category: 'Shoulders',
    defaultSets: 4,
    defaultReps: '12-15',
  },
  { id: 'ex-18', name: 'Face Pulls', category: 'Shoulders', defaultSets: 3, defaultReps: '15' },
  {
    id: 'ex-19',
    name: 'Front Dumbbell Raise',
    category: 'Shoulders',
    defaultSets: 3,
    defaultReps: '12',
  },

  // Arms
  {
    id: 'ex-20',
    name: 'Triceps Overhead Extension',
    category: 'Arms',
    defaultSets: 3,
    defaultReps: '10-12',
  },
  { id: 'ex-21', name: 'Triceps Pushdown', category: 'Arms', defaultSets: 3, defaultReps: '10-12' },
  {
    id: 'ex-22',
    name: 'Barbell Bicep Curl',
    category: 'Arms',
    defaultSets: 3,
    defaultReps: '10-12',
  },
  {
    id: 'ex-23',
    name: 'Dumbbell Hammer Curl',
    category: 'Arms',
    defaultSets: 3,
    defaultReps: '10-12',
  },

  // Core / Abs
  { id: 'ex-24', name: 'Plank', category: 'Core', defaultSets: 3, defaultReps: '60s' },
  {
    id: 'ex-25',
    name: 'Hanging Leg Raise',
    category: 'Core',
    defaultSets: 3,
    defaultReps: '12-15',
  },
  {
    id: 'ex-28',
    name: 'Cable Crunch (Upper Abs)',
    category: 'Core',
    defaultSets: 3,
    defaultReps: '12-15',
  },
  {
    id: 'ex-29',
    name: 'Russian Twists (Obliques)',
    category: 'Core',
    defaultSets: 3,
    defaultReps: '20',
  },
  { id: 'ex-30', name: 'Bicycle Crunches', category: 'Core', defaultSets: 3, defaultReps: '15-20' },
  { id: 'ex-31', name: 'Ab Wheel Rollout', category: 'Core', defaultSets: 3, defaultReps: '10-12' },
  { id: 'ex-32', name: 'Mountain Climbers', category: 'Core', defaultSets: 3, defaultReps: '45s' },
  {
    id: 'ex-33',
    name: 'Side Plank (Obliques)',
    category: 'Core',
    defaultSets: 3,
    defaultReps: '45s per side',
  },
  {
    id: 'ex-34',
    name: 'Reverse Crunch (Lower Abs)',
    category: 'Core',
    defaultSets: 3,
    defaultReps: '12-15',
  },

  // Cardio
  {
    id: 'ex-26',
    name: 'Treadmill Running',
    category: 'Cardio',
    defaultSets: 1,
    defaultReps: '20 mins',
  },
  {
    id: 'ex-27',
    name: 'Stationary Cycling',
    category: 'Cardio',
    defaultSets: 1,
    defaultReps: '30 mins',
  },
];

export const DEFAULT_DAY1_EXERCISES: PlanExercise[] = [
  {
    id: 'd1-ex-1',
    exerciseId: 'ex-1',
    name: 'Incline Chest Press',
    category: 'Chest',
    targetSets: 4,
    targetReps: '8-12',
  },
  {
    id: 'd1-ex-2',
    exerciseId: 'ex-2',
    name: 'Flat Chest Press',
    category: 'Chest',
    targetSets: 4,
    targetReps: '8-12',
  },
  {
    id: 'd1-ex-3',
    exerciseId: 'ex-16',
    name: 'Shoulder Press',
    category: 'Shoulders',
    targetSets: 4,
    targetReps: '8-12',
  },
  {
    id: 'd1-ex-4',
    exerciseId: 'ex-17',
    name: 'Lateral Raises',
    category: 'Shoulders',
    targetSets: 4,
    targetReps: '12-15',
  },
  {
    id: 'd1-ex-5',
    exerciseId: 'ex-20',
    name: 'Triceps Overhead Extension',
    category: 'Arms',
    targetSets: 3,
    targetReps: '10-12',
  },
  {
    id: 'd1-ex-6',
    exerciseId: 'ex-21',
    name: 'Triceps Pushdown',
    category: 'Arms',
    targetSets: 3,
    targetReps: '10-12',
  },
];

export const DEFAULT_DAY2_EXERCISES: PlanExercise[] = [
  {
    id: 'd2-ex-1',
    exerciseId: 'ex-7',
    name: 'Horizontal Pull (Seated Row)',
    category: 'Back',
    targetSets: 4,
    targetReps: '8-10',
  },
  {
    id: 'd2-ex-2',
    exerciseId: 'ex-8',
    name: 'Horizontal Pull (Chest-Supported Row)',
    category: 'Back',
    targetSets: 4,
    targetReps: '8-10',
  },
  {
    id: 'd2-ex-3',
    exerciseId: 'ex-6',
    name: 'Vertical Pull (Lat Pulldown)',
    category: 'Back',
    targetSets: 4,
    targetReps: '8-12',
  },
  {
    id: 'd2-ex-4',
    exerciseId: 'ex-18',
    name: 'Rear Delt Flyes / Reverse Fly',
    category: 'Shoulders',
    targetSets: 3,
    targetReps: '12-15',
  },
  {
    id: 'd2-ex-5',
    exerciseId: 'ex-22',
    name: 'Preacher Bicep Curl',
    category: 'Arms',
    targetSets: 3,
    targetReps: '10-12',
  },
  {
    id: 'd2-ex-6',
    exerciseId: 'ex-23',
    name: 'Incline Dumbbell Bicep Curl',
    category: 'Arms',
    targetSets: 3,
    targetReps: '10-12',
  },
];

export const DEFAULT_DAY3_EXERCISES: PlanExercise[] = [
  {
    id: 'd3-ex-1',
    exerciseId: 'ex-10',
    name: 'Squat Pattern (Barbell Squat)',
    category: 'Legs',
    targetSets: 4,
    targetReps: '8-10',
  },
  {
    id: 'd3-ex-2',
    exerciseId: 'ex-11',
    name: 'Leg Press',
    category: 'Legs',
    targetSets: 4,
    targetReps: '10-12',
  },
  {
    id: 'd3-ex-3',
    exerciseId: 'ex-12',
    name: 'RDL (Romanian Deadlift)',
    category: 'Legs',
    targetSets: 4,
    targetReps: '8-10',
  },
  {
    id: 'd3-ex-4',
    exerciseId: 'ex-13',
    name: 'Leg Extension',
    category: 'Legs',
    targetSets: 3,
    targetReps: '12-15',
  },
  {
    id: 'd3-ex-5',
    exerciseId: 'ex-14',
    name: 'Leg Curl',
    category: 'Legs',
    targetSets: 3,
    targetReps: '12-15',
  },
  {
    id: 'd3-ex-6',
    exerciseId: 'ex-15',
    name: 'Calf Raises',
    category: 'Legs',
    targetSets: 4,
    targetReps: '15-20',
  },
];

export const DEFAULT_DAY5_EXERCISES: PlanExercise[] = [
  {
    id: 'd5-ex-1',
    exerciseId: 'ex-1',
    name: 'Incline Chest Press',
    category: 'Chest',
    targetSets: 4,
    targetReps: '8-12',
  },
  {
    id: 'd5-ex-2',
    exerciseId: 'ex-6',
    name: 'Vertical Pull (Lat Pulldown)',
    category: 'Back',
    targetSets: 4,
    targetReps: '8-12',
  },
  {
    id: 'd5-ex-3',
    exerciseId: 'ex-16',
    name: 'Shoulder Press',
    category: 'Shoulders',
    targetSets: 4,
    targetReps: '8-12',
  },
  {
    id: 'd5-ex-4',
    exerciseId: 'ex-17',
    name: 'Lateral Raises',
    category: 'Shoulders',
    targetSets: 4,
    targetReps: '12-15',
  },
  {
    id: 'd5-ex-5',
    exerciseId: 'ex-22',
    name: 'Preacher Bicep Curl',
    category: 'Arms',
    targetSets: 3,
    targetReps: '10-12',
  },
  {
    id: 'd5-ex-6',
    exerciseId: 'ex-21',
    name: 'Triceps Pushdown',
    category: 'Arms',
    targetSets: 3,
    targetReps: '10-12',
  },
];

export const DEFAULT_DAY6_EXERCISES: PlanExercise[] = [
  {
    id: 'd6-ex-1',
    exerciseId: 'ex-12',
    name: 'RDL (Romanian Deadlift)',
    category: 'Legs',
    targetSets: 4,
    targetReps: '8-10',
  },
  {
    id: 'd6-ex-2',
    exerciseId: 'ex-29',
    name: 'Split Squat (Bulgarian / Dumbbell)',
    category: 'Legs',
    targetSets: 4,
    targetReps: '10-12',
  },
  {
    id: 'd6-ex-3',
    exerciseId: 'ex-14',
    name: 'Hamstring Curl',
    category: 'Legs',
    targetSets: 3,
    targetReps: '12-15',
  },
  {
    id: 'd6-ex-4',
    exerciseId: 'ex-13',
    name: 'Leg Extension',
    category: 'Legs',
    targetSets: 3,
    targetReps: '12-15',
  },
  {
    id: 'd6-ex-5',
    exerciseId: 'ex-30',
    name: 'Back Extension (Hyperextension)',
    category: 'Back',
    targetSets: 3,
    targetReps: '12-15',
  },
  {
    id: 'd6-ex-6',
    exerciseId: 'ex-15',
    name: 'Calf Raises',
    category: 'Legs',
    targetSets: 4,
    targetReps: '15-20',
  },
];

export const DEFAULT_INITIAL_PLAN: PlanDay[] = [
  {
    dayIndex: 0,
    dayName: 'Day 1',
    title: 'Chest, Shoulders & Triceps',
    isRestDay: false,
    exercises: DEFAULT_DAY1_EXERCISES,
  },
  {
    dayIndex: 1,
    dayName: 'Day 2',
    title: 'Back, Rear Delt & Biceps',
    isRestDay: false,
    exercises: DEFAULT_DAY2_EXERCISES,
  },
  {
    dayIndex: 2,
    dayName: 'Day 3',
    title: 'Legs & Calves',
    isRestDay: false,
    exercises: DEFAULT_DAY3_EXERCISES,
  },
  {
    dayIndex: 3,
    dayName: 'Day 4',
    title: 'Rest & Recovery',
    isRestDay: true,
    exercises: [],
  },
  {
    dayIndex: 4,
    dayName: 'Day 5',
    title: 'Upper Body (Chest, Back, Shoulders & Arms)',
    isRestDay: false,
    exercises: DEFAULT_DAY5_EXERCISES,
  },
  {
    dayIndex: 5,
    dayName: 'Day 6',
    title: 'Lower Body (Legs, Glutes & Calves)',
    isRestDay: false,
    exercises: DEFAULT_DAY6_EXERCISES,
  },
  {
    dayIndex: 6,
    dayName: 'Day 7',
    title: 'Rest & Active Recovery',
    isRestDay: true,
    exercises: [],
  },
];
